### ISSUE TITLE
Preprocess image for a generic tensorflow model

### ISSUE THREAD

**Issue by luistelmocosta** [marcotcr/lime#321]
Hello, I'm having an hard time processing one image to run on a tensorflow model, in this case DeepLabV3. 

```
#------------------
            # Exec network
            #------------------
            batch_probabilities_np= sess.run(
                probabilities_tf,
                feed_dict={
                    batch_images_tf: test_input_image_batch
                })

            import lime 
            from lime import lime_image

            explainer = lime_image.LimeImageExplainer()
            imageFilename = ["test_2.png"]
            image = transform_img_fn(imageFilename)

            explanation = explainer.explain_instance(image, batch_probabilities_np, top_labels=5, hide_color=0)
```
When I try this, I get the following error:

```
Traceback (most recent call last):
  File "test_lc.py", line 179, in <module>
    explanation = explainer.explain_instance(image, batch_probabilities_np, top_labels=5, hide_color=0)
  File "/usr/local/lib/python3.6/dist-packages/lime/lime_image.py", line 176, in explain_instance
    segments = segmentation_fn(image)
  File "/usr/local/lib/python3.6/dist-packages/lime/wrappers/scikit_image.py", line 117, in __call__
    return self.target_fn(args[0], **self.target_params)
  File "/usr/local/lib/python3.6/dist-packages/skimage/segmentation/_quickshift.py", line 68, in quickshift
    image = ndi.gaussian_filter(image, [sigma, sigma, 0])
  File "/usr/local/lib/python3.6/dist-packages/scipy/ndimage/filters.py", line 346, in gaussian_filter
    sigmas = _ni_support._normalize_sequence(sigma, input.ndim)
  File "/usr/local/lib/python3.6/dist-packages/scipy/ndimage/_ni_support.py", line 65, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank
```

What kind of image preprocessing to do in order to run my explainer? Could you please do some generic image preprocessing and not only for inception_v3?

Regards

**Comment by marcotcr** [comment]
See #69. 
Summary: the input to explain_image must be something that skimage can understand (a normal image) rather than a preprocessed image. Wrap the preprocessing in your prediction function, e.g.:
```
def predict_fn(x):
    model.predict(preprocess_input(x))
```
