### ISSUE TITLE
AttributeError: 'QuartileDiscretizer' object has no attribute 'undiscretize_idxs'

### ISSUE THREAD

**Issue by apremgeorge** [marcotcr/lime#357]
Lime explanation worked perfectly in python environment, also in local tornado api from postman call, 
I created docker image, while running docker image I am getting the following error
```
[E 190716 09:53:36 Tornado6.0:162] Traceback (most recent call last):
      File "C:\app\Tornado6.0.py", line 179, in _blocking_predict
        explanation = self.explanationCall(explainer, X_exp, model.predict_proba)
      File "C:\app\Tornado6.0.py", line 168, in explanationCall
        exp_data = explainer.explain_instance(instance, predict_fn, num_features=6)
      File "C:\Python\lib\site-packages\lime\lime_tabular.py", line 337, in explain_instance
        data, inverse = self.__data_inverse(data_row, num_samples)
      File "C:\Python\lib\site-packages\lime\lime_tabular.py", line 547, in __data_inverse
        inverse[1:] = self.discretizer.undiscretize(inverse[1:])
      File "C:\Python\lib\site-packages\lime\discretize.py", line 158, in undiscretize
        for x in ret[:, feature]])
      File "C:\Python\lib\site-packages\lime\discretize.py", line 158, in <listcomp>
        for x in ret[:, feature]])
      File "C:\Python\lib\site-packages\lime\discretize.py", line 127, in get_undiscretize_value
        if self.undiscretize_idxs[feature][val] == self.precompute_size:
    AttributeError: 'QuartileDiscretizer' object has no attribute 'undiscretize_idxs'
```
Dont understand why this docker run should throw this error, may i know how to solve this please?

**Comment by apremgeorge** [comment]
discretize_continuous=False removed the Error in docker run, 

discretize_continuous=True, discretizer='quartile' Throwing error in docker run, in local python env running perfect
