### ISSUE TITLE
reshape array error in RecurrentTabularExplainer?

### ISSUE THREAD

**Issue by apremgeorge** [marcotcr/lime#376]
Hi,
I build the keras model
below is the prediction from that
```
testData_for_model.shape
Out[300]: (1, 27)

Keras_model.predict_proba(testData_for_model)
Out[301]: array([[0.6559619]], dtype=float32)
```
For Explanation using RecurrentTabularExplainer, I convert train_data(input_x) to 3d array
```
input_x.shape
Out[302]: (10000, 27)
input_x_reshape = input_x.reshape(input_x.shape[0], 1, input_x.shape[1])
input_x_reshape.shape
Out[304]: (10000, 1, 27)
keras_explainer = lime.lime_tabular.RecurrentTabularExplainer(input_x_reshape, 
                                                 mode='classification',
                                                 feature_names=feature_names,
                                                 kernel_width=5,
                                                 random_state=42,
                                                 verbose=True,
                                                 discretize_continuous=False) 
```
As RecurrentTabularExplainer requires 2d array, I pass the testData_for_model in the explain_instance
```
exp = keras_explainer.explain_instance(testData_for_model, Keras_model.predict_proba, num_features = 10)
Traceback (most recent call last):

  File "<ipython-input-311-d9118569389e>", line 1, in <module>
    exp = keras_explainer.explain_instance(testData_for_model, Keras_model.predict_proba, num_features = 10)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lime\lime_tabular.py", line 631, in explain_instance
    model_regressor=model_regressor)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lime\lime_tabular.py", line 320, in explain_instance
    yss = predict_fn(inverse)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lime\lime_tabular.py", line 583, in predict_proba
    return func(X)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 245, in predict_proba
    preds = self.predict(x, batch_size, verbose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))

ValueError: Error when checking input: expected dense_474_input to have 2 dimensions, but got array with shape (5000, 1, 27)
```
May I please know my mistake here, may I know while modelling we need some changes
Thanks

**Comment by apremgeorge** [comment]
I tried the solution from https://github.com/keras-team/keras/issues/10123 by @EoinKenny

```
def predictKeras(testData_for_model):
    prediction_Class_1 = Keras_model.predict_proba(testData_for_model) 
    x = numpy.zeros((prediction_Class_1.shape[0], 1))
    probability = (x + 1) - prediction_Class_1
    final = numpy.append(probability,prediction_Class_1, axis=1)
    return final
```
The output of final is
```
final
Out[71]: array([[0.3440381‬, 0.6559619]])
```
Then I call
```
keras_explainer = lime.lime_tabular.LimeTabularExplainer(input_x, 
                                                 mode='classification',
                                                 feature_names=feature_names,
                                                 kernel_width=5,
                                                 random_state=42,
                                                 discretize_continuous=False) 
exp = keras_explainer.explain_instance(testData_for_model, predictKeras, num_features = 10)
```
Still I get following error
```
exp = keras_explainer.explain_instance(testData_for_model, predictKeras, num_features = 10)
Traceback (most recent call last):

  File "<ipython-input-72-c382c48d0eeb>", line 1, in <module>
    exp = keras_explainer.explain_instance(testData_for_model, predictKeras, num_features = 10)

  File "C:\ProgramData\Anaconda3\lib\site-packages\lime\lime_tabular.py", line 366, in explain_instance
    values = self.convert_and_round(data_row)

  File "C:\ProgramData\Anaconda3\lib\site-packages\lime\lime_tabular.py", line 257, in convert_and_round
    return ['%.2f' % v for v in values]

  File "C:\ProgramData\Anaconda3\lib\site-packages\lime\lime_tabular.py", line 257, in <listcomp>
    return ['%.2f' % v for v in values]

TypeError: only size-1 arrays can be converted to Python scalars
```
