### ISSUE TITLE
TypeError: <method-wrapper '__call__' of builtin_function_or_method object> is not a Python function

### ISSUE THREAD

**Issue by plannapus** [marcotcr/lime#422]
Hi,
I'm trying to apply `explain_instance` to the results of a CNN using MobileNet (via tensorflow) but keep getting the following error, no matter which parameter I modify:

```
>>> img.shape
(1, 224, 224, 3)
>>> predict_fn(img)
array([[4.77335675e-07, 6.21444087e-06, 2.32887596e-01, 2.64239721e-02,
        2.07287865e-03, 3.09167881e-05, 4.25639749e-01, 1.51046415e-05,
        3.96482610e-05, 2.32012717e-05, 1.31119194e-03, 1.00831080e-07,
        6.23450136e-09, 1.17117527e-03, 2.71290030e-08, 3.10377657e-01]],
      dtype=float32)
>>> explainer = lime_image.LimeImageExplainer()
>>> explainer.explain_instance(img, predict_fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/lime/lime_image.py", line 179, in explain_instance
    random_seed=random_seed)
  File "/usr/local/lib/python2.7/site-packages/lime/wrappers/scikit_image.py", line 105, in __init__
    kwargs = self.filter_params(quickshift)
  File "/usr/local/lib/python2.7/site-packages/lime/wrappers/scikit_image.py", line 84, in filter_params
    if has_arg(fn, name):
  File "/usr/local/lib/python2.7/site-packages/lime/utils/generic_utils.py", line 21, in has_arg
    arg_spec = inspect.getargspec(fn.__call__)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.py", line 825, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method-wrapper '__call__' of builtin_function_or_method object at 0x1241d4c80> is not a Python function
```

Any idea of how to debug this?  
Thanks in advances!

**Comment by marcotcr** [comment]
try `explainer.explain_instance(img[0], predict_fn)`, reopen if it doesn't work : )
