### ISSUE TITLE
Whether explainer returns the plot for highest probability prediction only?

### ISSUE THREAD

**Issue by apremgeorge** [marcotcr/lime#472]
Hi, I do a anomaly detection from a model and returns the probability for a record, the actual value for the feature is not an outlier, so I get probabilities 
"Inlier" = 89.84% and "outlier" = 10.16%
and explanation weights given as -0.06724317172140935
![image](https://user-images.githubusercontent.com/30790120/84336084-df402f80-abd9-11ea-9994-8c828f4e1624.png)
and the plot as
![image](https://user-images.githubusercontent.com/30790120/84336125-f252ff80-abd9-11ea-8502-798465a13de8.png)

Next, i do a prediction for another data, actual value for the feature is a outlier, so i get 
"Inlier" = 2.65% and "outlier" = 97.34%
and explanation weights given as -0.0711641914761484
![image](https://user-images.githubusercontent.com/30790120/84336200-20384400-abda-11ea-9483-9297be8afa84.png)
and the plot as
![image](https://user-images.githubusercontent.com/30790120/84336222-2a5a4280-abda-11ea-928a-2437b56b3b94.png)

Only seeing the explanation plot i couldn't differentiate the two, 
explainer returns for highest probability value
may i know how to revert for the first one to show as a not a outlier.

I tried top_labels=1 for the first case, throws error
![image](https://user-images.githubusercontent.com/30790120/84338303-0baa7a80-abdf-11ea-921b-8a5589fceb9a.png)

````
fig = exp.as_pyplot_figure()
Traceback (most recent call last):

  File "<ipython-input-100-0715b5937d23>", line 1, in <module>
    fig = exp.as_pyplot_figure()

  File "C:\Users\PremGeorgeAlphonse\Anaconda3\lib\site-packages\lime\explanation.py", line 169, in as_pyplot_figure
    exp = self.as_list(label=label, **kwargs)

  File "C:\Users\PremGeorgeAlphonse\Anaconda3\lib\site-packages\lime\explanation.py", line 143, in as_list
    ans = self.domain_mapper.map_exp_ids(self.local_exp[label_to_use], **kwargs)

KeyError: 1
````
For second case it is working
Thanks

**Comment by apremgeorge** [comment]
Fixed it, Thanks
