### ISSUE TITLE
Multithreading Lime within for loop

### ISSUE THREAD

**Issue by cauchyturing** [marcotcr/lime#82]
Hi, I am trying to runthe lime explainer for 40000+ samples, the model is a deep nn bundled in keras. below is my code

```
def _exp(i,queue = 0):
    c = 0
    exp = []
    explanation = explainer.explain_instance(data[i,:-1], predict_fn, top_labels=4)
    #explanation.show_in_notebook()
    exp_l = []
    for l in explanation.top_labels:

        exp_t = explanation.as_list(l)
        exp_l.append(exp_t)
    exp.append(exp_l)

from joblib import Parallel, delayed
import multiprocessing

results = Parallel(4)(delayed(_exp)(i) for i in xrange(16))
```

Then the error is like

```
Traceback (most recent call last):
  File "Claim_individual_top_k_group_reason_code_v2_lime.py", line 1200, in <module>
    results = pool.map(_exp, inputs)
  File "/home/wangz/anaconda2/envs/DIQ/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/wangz/anaconda2/envs/DIQ/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

Does anyone successfully parallelize lime on a single machine?

Thanks!

**Comment by FlorentPajot** [comment]
Could you please share the code used to instanciate your explainer, and as much information as you can to reproduce the error?

The error seems to be related to a function loaded from pickle which is not pickable. And you might find the answer here: https://stackoverflow.com/questions/8804830/python-multiprocessing-pickling-error

**Comment by echo66** [comment]
The current version of LIME is not suitable to do what you guys want to do. There are several reasons for me to say this and the usage of lambdas is one of them (assuming you want to serialize objects using `pickle`).

**Comment by marcotcr** [comment]
closing due to inactivity
